name: IPIdentify
version: 1.0
main: net.chunk64.IPIdentify.IPIdentify
commands:
    ipidentify:
        usage: /<command>
        description: IPIdentify commands.
        aliases: ipi
        permission: ipidentify.ipidentify